image: node:20-alpine

stages:
  - test
  - build
  - release

## Install stage ###################################################################

install:
  stage: .pre
  script:
    - npm ci --cache .npm --prefer-offline
    - npm install

  cache:
    - key: ${CI_JOB_NAME}
      paths:
        - .npm/
      when: on_success
  artifacts:
    paths:
      - node_modules/

## Test stage ###################################################################

test:
  stage: test
  needs:
    - job: install
  script:
    - npm run test

test-js-build:
  stage: test
  needs:
    - job: install
      artifacts: true
  script:
    - npm run build

lint:
  stage: test
  needs:
    - job: install
      artifacts: true
  script:
    - npm run lint

## Build stage ###################################################################

build:
  stage: build
  script:
    - npm run build
    - mv dist turris-webapps-${CI_COMMIT_SHORT_SHA}
    - cp turris-root.conf turris-webapps-json-cgi turris-webapps-${CI_COMMIT_SHORT_SHA}/
    - tar cvzf "turris-webapps-${CI_COMMIT_SHORT_SHA}.tar.gz" turris-webapps-${CI_COMMIT_SHORT_SHA}

  artifacts:
    paths:
      - turris-webapps-*.tar.gz

## Release stage ###################################################################

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: "$CI_COMMIT_TAG"
  needs:
    - job: build
      artifacts: true
  before_script:
    - apk update
    - apk add bash curl
  script:
    - .gitlab-ci/release.sh
