image: node:16-slim

stages:
  - test
  - build
  - release

cache:
    paths:
        - ./node_modules/

## Test stage ###################################################################

test:
    stage: test
    script:
        - npm test

test-js-build:
    stage: test
    script:
        - npm run-script build -- -o /tmp/app.min.js

lint:
    stage: test
    script:
        - npm install
        - npm run lint

## Build stage ###################################################################

build:
    stage: build
    script:
        - npm run build
        - mv build turris-webapps-${CI_COMMIT_SHORT_SHA}
        - cp turris-root.conf turris-webapps-json-cgi turris-webapps-${CI_COMMIT_SHORT_SHA}/
        - tar cvzf "turris-webapps-${CI_COMMIT_SHORT_SHA}.tar.gz" turris-webapps-${CI_COMMIT_SHORT_SHA}

    artifacts:
        paths:
        - turris-webapps-*.tar.gz

## Release stage ###################################################################

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_COMMIT_TAG'
  needs:
    - job: build
      artifacts: true
  before_script:
    - apk update
    - apk add bash curl
  script:
    - .gitlab-ci/release.sh
